In [13]:
import os
import pandas as pd

# This traverses up to the project root regardless of notebook depth
root = os.path.abspath(os.path.join(os.getcwd(), '..', '..')) 
path = os.path.join(root, 'dataset', 'train.csv')

train = pd.read_csv(path)

In [14]:
train = train[train["label"] == 0]

In [15]:
train.head()

,image_path,annotation_path,label,x1,y1,x2,y2,source_folder
0,Test\Images\124\0003.jpg,Test\Annotations\124\0003.txt,0,NaN,NaN,NaN,NaN,124
1,Test\Images\147\0302.jpg,Test\Annotations\147\0302.txt,0,NaN,NaN,NaN,NaN,147
8,Test\Images\133\0197.jpg,Test\Annotations\133\0197.txt,0,NaN,NaN,NaN,NaN,133
23,Test\Images\136\0136.jpg,Test\Annotations\136\0136.txt,0,NaN,NaN,NaN,NaN,136
29,Test\Images\136\0277.jpg,Test\Annotations\136\0277.txt,0,NaN,NaN,NaN,NaN,136

In [16]:
train.describe()

        label   x1   y1   x2   y2  source_folder
count  1724.0  0.0  0.0  0.0  0.0    1724.000000
mean      0.0  NaN  NaN  NaN  NaN     131.672274
std       0.0  NaN  NaN  NaN  NaN      15.003924
min       0.0  NaN  NaN  NaN  NaN     101.000000
25%       0.0  NaN  NaN  NaN  NaN     120.000000
50%       0.0  NaN  NaN  NaN  NaN     133.000000
75%       0.0  NaN  NaN  NaN  NaN     147.000000
max       0.0  NaN  NaN  NaN  NaN     160.000000

In [18]:
import tensorflow as tf 
from tensorflow.keras import layers, Model

ModuleNotFoundError: No module named 'tensorflow'