In [13]:
import os
import pandas as pd

# This traverses up to the project root regardless of notebook depth
root = os.path.abspath(os.path.join(os.getcwd(), '..', '..')) 
path = os.path.join(root, 'dataset', 'train.csv')

train = pd.read_csv(path)

In [14]:
train = train[train["label"] == 0]

In [15]:
train.head()

,image_path,annotation_path,label,x1,y1,x2,y2,source_folder
0,Test\Images\124\0003.jpg,Test\Annotations\124\0003.txt,0,NaN,NaN,NaN,NaN,124
1,Test\Images\147\0302.jpg,Test\Annotations\147\0302.txt,0,NaN,NaN,NaN,NaN,147
8,Test\Images\133\0197.jpg,Test\Annotations\133\0197.txt,0,NaN,NaN,NaN,NaN,133
23,Test\Images\136\0136.jpg,Test\Annotations\136\0136.txt,0,NaN,NaN,NaN,NaN,136
29,Test\Images\136\0277.jpg,Test\Annotations\136\0277.txt,0,NaN,NaN,NaN,NaN,136

In [16]:
train.describe()

        label   x1   y1   x2   y2  source_folder
count  1724.0  0.0  0.0  0.0  0.0    1724.000000
mean      0.0  NaN  NaN  NaN  NaN     131.672274
std       0.0  NaN  NaN  NaN  NaN      15.003924
min       0.0  NaN  NaN  NaN  NaN     101.000000
25%       0.0  NaN  NaN  NaN  NaN     120.000000
50%       0.0  NaN  NaN  NaN  NaN     133.000000
75%       0.0  NaN  NaN  NaN  NaN     147.000000
max       0.0  NaN  NaN  NaN  NaN     160.000000

In [20]:
import sys
!{sys.executable} -m pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.21.0-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (6.33.6)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (2.33.0)
Requirement already satisfied: setuptools in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Using cached wrapt-2.2.2-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Using cached grpcio-1.82.1-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Using cached keras-3.15.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (2.4.3)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Using cached h5py-3.14.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Using cached ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (1.26.20)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Using cached wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras>=3.12.0->tensorflow)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.12.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Using cached optree-0.19.1-cp311-cp311-win_amd64.whl.metadata (32 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.12.0->tensorflow)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Lenovo\AppData\Roaming\Python\Python311\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached tensorflow-2.21.0-cp311-cp311-win_amd64.whl (350.8 MB)
Using cached grpcio-1.82.1-cp311-cp311-win_amd64.whl (5.0 MB)
Using cached h5py-3.14.0-cp311-cp311-win_amd64.whl (2.9 MB)
Using cached ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl (210 kB)
Using cached absl_py-2.5.0-py3-none-any.whl (137 kB)
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Using cached wheel-0.47.0-py3-none-any.whl (32 kB)
Using cached flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Using cached gast-0.7.0-py3-none-any.whl (22 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Using cached keras-3.15.0-py3-none-any.whl (1.7 MB)
Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Using cached termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Using cached wrapt-2.2.2-cp311-cp311-win_amd64.whl (80 kB)
Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)
Using cached optree-0.19.1-cp311-cp311-win_amd64.whl (337 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, libclang, flatbuffers, wrapt, wheel, termcolor, optree, opt_einsum, ml_dtypes, mdurl, h5py, grpcio, google_pasta, gast, absl-py, markdown-it-py, astunparse, rich, keras, tensorflow

   -- -------------------------------------  1/20 [libclang]
   -- -------------------------------------  1/20 [libclang]
   -- -------------------------------------  1/20 [libclang]
   -- -------------------------------------  1/20 [libclang]
   -- -------------------------------------  1/20 [libclang]
   ---- -----------------------------------  2/20 [flatbuffers]
   ---- -----------------------------------  2/20 [flatbuffers]
   ------ ---------------------------------  3/20 [wrapt]
   ------ ---------------------------------  3/20 [wrapt]
   -------- -------------------------------  4/20 [wheel]
   -------- -------------------------------  4/20 [wheel]
   -------- -------------------------------  4/20 [wheel]
   ---------- -----------------------------  5/20 [termcolor]
   ------------ ---------------------------  6/20 [optree]
   ------------ ---------------------------  6/20 [optree]
   ------------ ---------------------------  6/20 [optree]
   -------------- -------------------------  7/20 [opt_einsum]
   -------------- -------------------------  7/20 [opt_einsum]
   -------------- -------------------------  7/20 [opt_einsum]
   -------------- -------------------------  7/20 [opt_einsum]
   ---------------- -----------------------  8/20 [ml_dtypes]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   -------------------- ------------------- 10/20 [h5py]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ---------------------- ----------------- 11/20 [grpcio]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   ------------------------ --------------- 12/20 [google_pasta]
   -------------------------- ------------- 13/20 [gast]
   -------------------------- ------------- 13/20 [gast]
   -------------------------- ------------- 13/20 [gast]
   -------------------------- ------------- 13/20 [gast]
   -------------------------- ------------- 13/20 [gast]
   -------------------------- ------------- 13/20 [gast]
   -------------------------- ------------- 13/20 [gast]
   ---------------------------- ----------- 14/20 [absl-py]
   ---------------------------- ----------- 14/20 [absl-py]
   ---------------------------- ----------- 14/20 [absl-py]
   ---------------------------- ----------- 14/20 [absl-py]
   ---------------------------- ----------- 14/20 [absl-py]
   ---------------------------- ----------- 14/20 [absl-py]
   ---------------------------- ----------- 14/20 [absl-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   ------------------------------ --------- 15/20 [markdown-it-py]
   -------------------------------- ------- 16/20 [astunparse]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ---------------------------------- ----- 17/20 [rich]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   ------------------------------------ --- 18/20 [keras]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]
   -------------------------------------- - 19/20 [tensorflow]

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip